version: '3'

services:
  web:
    platform: linux/amd64
    container_name: web
    image: web:latest
    build:
      context: .
      target: runner
      args:
        APP_ENV: production
        NEXT_PUBLIC_BASE_URL: https://mcv-user.rkincubator.dev
        NEXT_PUBLIC_API_ENDPOINT: https://mcv-backend.rkincubator.dev/graphql
        NEXT_PUBLIC_IMAGE_URL: https://mcv-storage.rkincubator.dev
        NEXT_PUBLIC_CHAIN_ID: 137
        RPC_ENDPOINT: https://polygon-rpc.com/
        NEXT_PUBLIC_COOKIE_DOMAIN: .rkincubator.dev
        NEXT_PUBLIC_CV_CREATION_BASE_URL: https://mcv-creation.rkincubator.dev
    environment:
      TERM: linux
      LANG: "C.UTF-8"
      LOG_ROTATION_DAY: 7
      NODE_ENV: production
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "2"
    restart: "always"
    ports:
      - 26701:6701
